package zsearch

var ExtMap = map[string]struct{}{
	".txt":   {},
	".xml":   {},
	".json":  {},
	".go":    {},
	".c":     {},
	".cpp":   {},
	".mod":   {},
	".sum":   {},
	".java":  {},
	".py":    {},
	".js":    {},
	".ts":    {},
	".vue":   {},
	".yaml":  {},
	".shell": {},
	".sh":    {},
	".bat":   {},
	".h":     {},
	".hpp":   {},
	".C":     {},
	".hxx":   {},
	".cc":    {},
	".cs":    {},
	".php":   {},
	".py3":   {},
	".kt":    {},
	".css":   {},
	".html":  {},
	".conf":  {},
	".cmd":   {},
}
